#!/bin/bash

# gets cryptocurrency rates
# BTC id=1, XMR id=328, ETH id=1027
curl -H "X-CMC_PRO_API_KEY: f9474327-4c7f-4712-ac0e-b4892c295a3f" https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?id=1,328,1027 > ~/Workspace/crypto-script/market-data/crypto-data

# gets foreign exchange rates
curl https://www.freeforexapi.com/api/live?pairs=EURUSD > ~/Workspace/crypto-script/market-data/eurusd
curl https://www.freeforexapi.com/api/live?pairs=USDRON > ~/Workspace/crypto-script/market-data/usdron
curl https://www.freeforexapi.com/api/live?pairs=USDHUF > ~/Workspace/crypto-script/market-data/usdhuf

